worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    upstream auth_service { server auth:8081; }
    upstream product_service { server product:8082; }
    upstream order_service { server order:8083; }
    upstream chat_service { server chat:8084; }
    upstream storage_service { server storage:8087; }
    upstream analytics_svc { server analytics:8088; }
    upstream nextjs_app { server web:3000; }
    upstream react_admin { server admin:3001; }

    server {
        listen 80;
        server_name localhost;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        location /api/auth/ {
            proxy_pass http://auth_service/;
        }

        location /api/products/ {
            proxy_pass http://product_service/;
        }

        location /api/orders/ {
            proxy_pass http://order_service/;
        }

        location /api/storage/ {
            proxy_pass http://storage_service/;
            client_max_body_size 600M;
        }

        location /api/analytics/ {
            proxy_pass http://analytics_svc/;
        }

        location /api/chat/ {
            proxy_pass http://chat_service/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location /admin/ {
            proxy_pass http://react_admin/;
        }

        location / {
            proxy_pass http://nextjs_app/;
        }
    }
}
